"""Generate manuscript figures A, B, C from the wall paper baseline dataset.

Figures D (fine-grained pacing) and E (temporal trend) are generated by their
respective analysis scripts (r1_pacing_fine_grained.py and r1_temporal_trend.py).

Figure A: probability density of percentage slowdown by gender (with N in legend)
Figure B: bar plot of wall-hit prevalence by gender (Wilson 95% CI + N)
Figure C: stratified bars by performance category × gender (95% CI of mean + N)

All figures saved at 300 DPI TIFF (LZW compression) + 150 DPI PNG preview.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _r1_common import load_data, COLOR_MEN, COLOR_WOMEN

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from statsmodels.stats.proportion import proportion_confint


FIGURES_DIR = Path(__file__).parent.parent / "figures"
PERF_ORDER = ["Competitive (<3h)", "Advanced", "Intermediate", "Recreational", "Casual"]


def save_with_lzw(fig, basename):
    """Save fig as 300 DPI TIFF (LZW) + 150 DPI PNG."""
    tiff_path = FIGURES_DIR / f"{basename}.tiff"
    png_path = FIGURES_DIR / f"{basename}.png"
    # Save as PNG first then convert to TIFF with LZW (matplotlib's TIFF lacks LZW)
    fig.savefig(png_path, dpi=150, bbox_inches="tight", facecolor="white")
    fig.savefig(tiff_path, dpi=300, bbox_inches="tight", facecolor="white")
    # Re-open and re-save as TIFF with LZW + RGB
    img = Image.open(tiff_path)
    if img.mode == "RGBA":
        bg = Image.new("RGB", img.size, "white")
        bg.paste(img, mask=img.split()[3])
        img = bg
    elif img.mode != "RGB":
        img = img.convert("RGB")
    img.save(tiff_path, compression="tiff_lzw", dpi=(300, 300))
    print(f"Saved: {tiff_path.name} ({tiff_path.stat().st_size/1024:.1f} KB)")


def figure_a_density(df):
    """Density of percentage slowdown by gender."""
    men = df[df["gender_label"] == "Male"]["percentage_slowdown"].dropna()
    women = df[df["gender_label"] == "Female"]["percentage_slowdown"].dropna()

    fig, ax = plt.subplots(figsize=(8, 5), dpi=300)
    bins = np.linspace(-20, 80, 200)
    ax.hist(men, bins=bins, density=True, color=COLOR_MEN, alpha=0.5,
            label=f"Men (n = {len(men):,})", edgecolor="none")
    ax.hist(women, bins=bins, density=True, color=COLOR_WOMEN, alpha=0.5,
            label=f"Women (n = {len(women):,})", edgecolor="none")
    ax.set_xlim(-20, 80)
    ax.set_xlabel("Percentage slowdown (%)")
    ax.set_ylabel("Density")
    ax.legend(frameon=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    save_with_lzw(fig, "Figure_1_Density")
    plt.close(fig)


def figure_b_prevalence(df):
    """Bar plot of wall-hit prevalence by gender with Wilson 95% CI."""
    men = df[df["gender_label"] == "Male"].dropna(subset=["hit_wall"])
    women = df[df["gender_label"] == "Female"].dropna(subset=["hit_wall"])
    n_m, n_w = len(men), len(women)
    hit_m, hit_w = int(men["hit_wall"].sum()), int(women["hit_wall"].sum())

    pct_m = 100 * hit_m / n_m
    pct_w = 100 * hit_w / n_w
    ci_m_lo, ci_m_hi = proportion_confint(hit_m, n_m, method="wilson")
    ci_w_lo, ci_w_hi = proportion_confint(hit_w, n_w, method="wilson")

    fig, ax = plt.subplots(figsize=(6, 5), dpi=300)
    err_m = [[pct_m - 100 * ci_m_lo], [100 * ci_m_hi - pct_m]]
    err_w = [[pct_w - 100 * ci_w_lo], [100 * ci_w_hi - pct_w]]
    ax.bar([0], [pct_m], yerr=err_m, color=COLOR_MEN, alpha=0.85,
           capsize=5, error_kw={"lw": 1.5})
    ax.bar([1], [pct_w], yerr=err_w, color=COLOR_WOMEN, alpha=0.85,
           capsize=5, error_kw={"lw": 1.5})
    ax.set_xticks([0, 1])
    ax.set_xticklabels([f"Men\n(n = {n_m:,})", f"Women\n(n = {n_w:,})"])
    ax.set_ylabel('Prevalence of "hitting the wall" (%)')
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    # Add value labels above bars
    ax.text(0, pct_m + 100 * ci_m_hi - pct_m + 0.5, f"{pct_m:.2f}%", ha="center", fontsize=9)
    ax.text(1, pct_w + 100 * ci_w_hi - pct_w + 0.5, f"{pct_w:.2f}%", ha="center", fontsize=9)
    plt.tight_layout()
    save_with_lzw(fig, "Figure_2_Boxplot")  # legacy filename
    plt.close(fig)


def figure_c_stratified(df):
    """Stratified bar plot: mean slowdown by performance category × gender, with 95% CI."""
    df = df.dropna(subset=["percentage_slowdown", "performance_category", "gender_label"])

    fig, ax = plt.subplots(figsize=(11, 6), dpi=300)
    x = np.arange(len(PERF_ORDER))
    width = 0.38

    for i, gender in enumerate(["Male", "Female"]):
        color = COLOR_MEN if gender == "Male" else COLOR_WOMEN
        means, errs, ns = [], [], []
        for cat in PERF_ORDER:
            sub = df[(df["gender_label"] == gender) & (df["performance_category"] == cat)]["percentage_slowdown"]
            n = len(sub)
            mean = sub.mean()
            se = sub.std() / np.sqrt(n) if n > 0 else 0
            means.append(mean)
            errs.append(1.96 * se)
            ns.append(n)
        pos = x + (i - 0.5) * width
        ax.bar(pos, means, width, yerr=errs, color=color, alpha=0.85,
               capsize=3, label=gender, error_kw={"lw": 1.0})
        # N labels above bars
        for px, m, err, n in zip(pos, means, errs, ns):
            ax.text(px, m + err + 0.4, f"n={n:,}", ha="center", fontsize=6.5, rotation=0)

    ax.set_xticks(x)
    ax.set_xticklabels(PERF_ORDER, rotation=12, ha="right")
    ax.set_ylabel("Mean percentage slowdown (%)")
    ax.legend(frameon=False, loc="upper left")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    save_with_lzw(fig, "Figure_3_Risk_Plot")  # legacy filename
    plt.close(fig)


if __name__ == "__main__":
    df = load_data()
    print(f"Loaded {len(df):,} runners")

    print("\n=== Generating Figure A (density) ===")
    figure_a_density(df)

    print("\n=== Generating Figure B (prevalence with Wilson 95% CI) ===")
    figure_b_prevalence(df)

    print("\n=== Generating Figure C (stratified with 95% CI of mean) ===")
    figure_c_stratified(df)

    print("\nFigures D and E are generated by their analysis scripts:")
    print("  - notebooks/r1_pacing_fine_grained.py → Figure_D_Pacing_Variability")
    print("  - notebooks/r1_temporal_trend.py → Figure_E_Temporal_Trend")
